
import time
import os
import subprocess

LOG_FILE = r"C:\Users\Chesley\Galactic AI\logs\main.log"
HEARTBEAT_FILE = r"C:\Users\Chesley\Galactic AI\logs\integrity_monitor.heartbeat"
HEALTH_REPORT = r"C:\Users\Chesley\Galactic AI\logs\HEALTH_REPORT.md"
CHECK_INTERVAL_SECONDS = 10

def write_heartbeat():
    with open(HEARTBEAT_FILE, "w") as f:
        f.write(str(int(time.time())))

def tail_log():
    try:
        with open(LOG_FILE, 'rb') as f:
            f.seek(-2048, 2) # Seek to the last 2KB
            return f.read().decode('utf-8', errors='ignore')
    except Exception:
        return ""

def check_for_errors(log_content):
    errors = []
    for line in log_content.splitlines():
        if "ERROR" in line or "CRITICAL" in line:
            errors.append(line)
    return errors

def update_health_report(new_errors):
    with open(HEALTH_REPORT, "a") as f:
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        f.write(f"\n--- Check at {timestamp} ---\n")
        if new_errors:
            f.write("🔴 New Errors Detected:\n")
            for error in new_errors:
                f.write(f"- `{error}`\n")
        else:
            f.write("🟢 No new critical errors found.\n")

def main():
    print("Integrity Monitor Started. Press Ctrl+C to stop.")
    if not os.path.exists(HEALTH_REPORT):
        with open(HEALTH_REPORT, "w") as f:
            f.write("# System Health Report\n")
            f.write("This report is automatically generated by the Integrity Monitor.\n")

    last_log_content = ""
    while True:
        write_heartbeat()
        
        current_log_content = tail_log()
        if current_log_content != last_log_content:
            new_content = current_log_content[len(last_log_content):]
            errors = check_for_errors(new_content)
            if errors:
                update_health_report(errors)
            last_log_content = current_log_content

        time.sleep(CHECK_INTERVAL_SECONDS)

if __name__ == "__main__":
    main()
