import os
import asyncio
import glob
from pathlib import Path
from skills.base import GalacticSkill

class MagicDocsSkill(GalacticSkill):
    """
    Auto-Context Mapping (MagicDocs)
    Continuously maintains a .galactic_map.md of the project architecture.
    """
    skill_name = "magic_docs"
    version = "1.0.0"
    author = "Galactic AI"
    description = "Automatically builds and maintains a project architecture map (.galactic_map.md)."
    category = "context"
    icon = "🗺️"

    def __init__(self, core):
        super().__init__(core)
        self.map_file = Path(self.core.config.get("paths", {}).get("workspace", "./workspace")) / ".galactic_map.md"

    async def run(self):
        """Background loop to periodically update the magic map."""
        workspace_dir = self.core.config.get('paths', {}).get('workspace', './workspace')
        
        while self.enabled:
            def _build_map():
                if not os.path.exists(workspace_dir):
                    return False
                    
                tree = []
                for root, dirs, files in os.walk(workspace_dir):
                    dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['__pycache__', 'node_modules']]
                    level = root.replace(workspace_dir, '').count(os.sep)
                    indent = ' ' * 4 * level
                    tree.append(f"{indent}- **{os.path.basename(root) or 'workspace'}/**")
                    subindent = ' ' * 4 * (level + 1)
                    for f in files:
                        if f.endswith(('.py', '.js', '.ts', '.html', '.css', '.md', '.json', '.yaml')) and not f.startswith('.'):
                            tree.append(f"{subindent}- `{f}`")

                map_content = "# Galactic MagicDocs: Project Architecture Map\n\n"
                map_content += "Auto-generated by MagicDocsSkill. Provides structural context for sub-agents.\n\n"
                map_content += "\n".join(tree)

                try:
                    current_content = self.map_file.read_text(encoding='utf-8') if self.map_file.exists() else ""
                    if current_content != map_content:
                        self.map_file.parent.mkdir(parents=True, exist_ok=True)
                        self.map_file.write_text(map_content, encoding='utf-8')
                        return True
                except Exception as e:
                    pass
                return False

            updated = await asyncio.to_thread(_build_map)
            if updated:
                await self.core.log("[MagicDocs] Updated .galactic_map.md", priority=2)
                
            await asyncio.sleep(300) # Update every 5 minutes

    def get_tools(self):
        return {
            "update_magic_docs": {
                "description": "Force an immediate update of the .galactic_map.md file.",
                "parameters": {"type": "object", "properties": {}},
                "fn": self._force_update
            }
        }

    async def _force_update(self, args):
        self.map_file.unlink(missing_ok=True)
        return "MagicDocs update triggered. The map will be regenerated on the next cycle."
